VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "yeti1" do |yeti1|

    vagrant1.vm.box = "ubuntu/xenial64"

    vagrant1.vm.network "forwarded_port", guest: 80, host: 8880

    yeti1.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision.yml"
        ansible.inventory_path = "hosts"
    end

  end

end

