VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/xenial64"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8877
    vagrant1.vm.network "forwarded_port", guest: 443, host: 7443
  end

  #config.vm.define "vagrant2" do |vagrant2|
  #  vagrant2.vm.box = "ubuntu/xenial64"
  #  vagrant2.vm.network "forwarded_port", guest: 80, host: 8878
  #  vagrant2.vm.network "forwarded_port", guest: 443, host: 7444
  #end
  #config.vm.define "vagrant3" do |vagrant3|
  #  vagrant3.vm.box = "ubuntu/xenial64"
  #  vagrant3.vm.network "forwarded_port", guest: 80, host: 8879
  #  vagrant3.vm.network "forwarded_port", guest: 443, host: 7445
  #end
end

